### ISSUE TITLE
ESLint error in IDE

### ISSUE THREAD

**Issue by piernik** [ckeditor/ckeditor5-package-generator#61] opened 2021-10-18 11:25 UTC
## 📝 Provide detailed reproduction steps (if any)

I'm using WebStorm IDE. Tool was installed in CMD window.

### ✔️ Expected result

All should work fine but I'm getting error in IDE

### ❌ Actual result

```
Error: Failed to load plugin 'ckeditor5-rules' declared in '.eslintrc.js » eslint-config-ckeditor5': Cannot find module 'eslint-plugin-ckeditor5-rules'
Require stack:
- C:\strony\www\libsJs\ckeditor5-info-box\__placeholder__.js

Error: Failed to load plugin 'ckeditor5-rules' declared in '.eslintrc.js » eslint-config-ckeditor5': Cannot find module 'eslint-plugin-ckeditor5-rules'
Require stack:
- C:\strony\www\libsJs\ckeditor5-info-box\__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at Object.resolve (C:\strony\www\libsJs\ckeditor5-info-box\node_modules\@eslint\eslintrc\lib\shared\relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (C:\strony\www\libsJs\ckeditor5-info-box\node_modules\@eslint\eslintrc\lib\config-array-factory.js:1017:39)
    at C:\strony\www\libsJs\ckeditor5-info-box\node_modules\@eslint\eslintrc\lib\config-array-factory.js:908:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (C:\strony\www\libsJs\ckeditor5-info-box\node_modules\@eslint\eslintrc\lib\config-array-factory.js:904:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\strony\www\libsJs\ckeditor5-info-box\node_modules\@eslint\eslintrc\lib\config-array-factory.js:725:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\strony\www\libsJs\ckeditor5-info-box\node_modules\@eslint\eslintrc\lib\config-array-factory.js:665:20)
Process finished with exit code -1

```

### ❓ Possible solution

Have no idea

## 📃 Other details

Using npm
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by pomek** [comment] 2021-10-18 11:55
Could you type `yarn/npm run lint` from CLI to verify does it work at all? `cwd` should point at `C:\strony\www\libsJs\ckeditor5-info-box`.

**Comment by pomek** [comment] 2021-10-19 06:42
That's weird as the `eslint-config-ckeditor5` package [requires](https://github.com/ckeditor/eslint-config-ckeditor5/blob/master/package.json#L15) [`eslint-plugin-ckeditor5-rules`](https://github.com/ckeditor/eslint-plugin-ckeditor5-rules/blob/master/package.json#L3), which cannot be found.

@przemyslaw-zan, could you check to reproduce the issue using Windows CMD console?

**Comment by pomek** [comment] 2021-11-09 09:43
We reproduced the issue, see: https://github.com/ckeditor/ckeditor5-package-generator/pull/73#issuecomment-963912032. It should be fixed soon.

**Comment by pomek** [comment] 2022-07-08 08:25
Closing due to lack of activity (missing steps for reproducing the issue).

**Closed by pomek** 2022-07-08 08:25 UTC
Labels: resolution:expired, squad:devops, type:bug
