### ISSUE TITLE
Enable verifying a commit using husky in a newly created package

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-package-generator#59] opened 2021-10-13 11:34 UTC
## Provide a description of the task

It's good to know whether a committed code passes the static analyzes. Hence, we could verify a commit using husky, similar to how we do in CKEditor 5.

**Comment by pomek** [comment] 2021-10-21 10:42
Example: https://github.com/ckeditor/ckeditor5/blob/4381eca98bfc2a21e7b6a765492f5bb647b62008/package.json#L174-L184

**Comment by przemyslaw-zan** [comment] 2021-11-03 11:56
As of now, the repository does not pass the `ckeditor5-dev-tests-check-dependencies` check:

```
$ yarn run ckeditor5-dev-tests-check-dependencies
yarn run v1.22.10
$ D:\Repo\ckeditor5-package-generator\node_modules\.bin\ckeditor5-dev-tests-check-dependencies
🔎 Checking dependencies in ckeditor5-package-generator...
🔥 Found some issue with dependencies in ckeditor5-package-generator.

❌ Missing devDependencies:
- sinon
- chai
- mockery

❌ Misplaced dependencies (`dependencies` or `devDependencies`):

The following packages are not used in the source and should be moved to `devDependencies`
- chalk
- cli-cursor
- cli-spinners
- commander
- glob
- is-interactive
- lodash.template
- mkdirp


🔎 Checking dependencies in @ckeditor/ckeditor5-package-tools...
🔥 Found some issue with dependencies in @ckeditor/ckeditor5-package-tools.

❌ Missing devDependencies:
- glob
- mkdirp
- terser-webpack-plugin
- chalk

❌ Unused dependencies:
- css-loader
- istanbul-instrumenter-loader
- karma-chai
- karma-chrome-launcher
- karma-coverage
- karma-mocha
- karma-mocha-reporter
- karma-sinon
- karma-sinon-chai
- karma-sourcemap-loader
- karma-webpack
- mocha
- postcss-loader
- raw-loader
- sinon-chai
- style-loader
- stylelint
- stylelint-config-ckeditor5

❌ Duplicated `dependencies` and `devDependencies`:
- chai

❌ Misplaced dependencies (`dependencies` or `devDependencies`):

The following packages are not used in the source and should be moved to `devDependencies`
- @ckeditor/ckeditor5-dev-utils
- karma
- minimist
- sinon
- webpack
- webpack-dev-server


error Command failed with exit code 1.
```

Moving some of these deps between `dependencies` and `devDependencies`, as well as fixing duplicates probably will not break anything. However, deps marked as `unused` and `missing` are, as far as i understand, caused by packaged complementing each other, and thus being intended. What do we do about this?

**Comment by psmyrek** [comment] 2021-11-03 12:29
Some of the errors found by the `check-dependencies` script are false positives, and it seems to me that we cannot blindly trust what it is now returning. This script is dedicated to the CKEditor 5 repo and it may not work properly with other repositories, because it checks if the package should belong to the `devDependencies` group basing on whether it was not used in either the `src` or the `theme` paths. In `ckeditor5-package-generator` we don't have such paths at all and the whole "production" source code is located in `lib` and `bin` paths. So now the `check-dependencies` script always says all packages should belong to `devDependencies` group, which of course is not true.

**Comment by pomek** [comment] 2021-11-04 08:28
I briefly scanned the attached log, and I'm not sure why the script checks the following directories:

* `🔎 Checking dependencies in ckeditor5-package-generator...`
* `🔎 Checking dependencies in @ckeditor/ckeditor5-package-tools...`

As @psmyrek mentioned, the dep-checker script works only in CKEditor 5 environment and should be used only in CKEditor 5 packages.

As for now, we can only execute linters when a developer tries to commit new changes in the **newly** created package.

**Comment by pomek** [comment] 2021-11-04 08:37
Bonus: I tried to use dep-checker in `ckeditor5-foo`:

```bash
pwd
/Users/pomek/Projects/tmp/ckeditor5-foo

node /Users/pomek/Projects/ckeditor/ckeditor5/node_modules/.bin/ckeditor5-dev-tests-check-dependencies .
# An empty output.
```

Unfortunately, changing `package.json` does not impact the script.

We could improve it but in the end, it means that we need to install `@ckeditor/ckeditor5-dev-tests` package in `cke5-foo` (which is heavy and perhaps may slow the installation time).

Hence, the package tools could deliver a simplified version of the dep-checker that will work only for a single package.

However, it's a feature and should be extracted to a separate issue.

**Comment by pomek** [comment] 2021-11-04 08:39
So, to clarify what the issue represents, when the developer wants to commit changes in the newly created package, we want to execute the git pre-commit hook for running eslint and stylelint.

**Comment by przemyslaw-zan** [comment] 2021-11-05 13:51
In order for `husky` to properly attach git hooks, initialization of git repository had to be moved before installation of the dependencies.

**Comment by przemyslaw-zan** [comment] 2021-11-08 15:38
Final approach we've decided to take is to run `npm rebuild husky` command after initializing repository.

*   Initially, husky did not work due to installation order (`'husky' is not recognized as an internal or external command...` error)
*   Initialising repository before installing dependencies [didn't always work](https://github.com/ckeditor/ckeditor5-package-generator/pull/73#pullrequestreview-799787136)
*   Including `postintall` hook `husky install` also requires to swap the order of installation, and does not seem to attach the hook correctly anyway
*   `yarn rebuild` can't be used in our project, since we use `yarn` v1, and `rebuild` was only introduced in v2, hence only `npm` script is available

**Closed** 2021-11-09 09:52 UTC
Labels: squad:devops, type:task
